### ISSUE TITLE
Symfony 7.1 support

### ISSUE THREAD

**Issue by jovic1987** [membrane-php/membrane-core#188]
Hello Chris,

Long time no see 😄 

May I ask you if you can adjust membrane-core to support SF 7.1 https://github.com/membrane-php/membrane-core/blob/main/composer.json#L21 

Thank you very much in advance

**Comment by carnage** [comment]
It's only been 10 months :) 

Needed a few dependencies updating through the whole set of packages but release 0.8.2 supports symfony 7 now

**Comment by developers-shared** [comment]
I really appreciate fast response and effort to help 💪 

However I think would need additional round of upgrade once [this](https://github.com/cebe/php-openapi/issues/211) is done as https://github.com/membrane-php/openapi-router is rely on this library and library itself doesn't support SF 7.1 just yet. 

Once I tried to update composer with release 0.8.2 I got which confirms it

`Root composer.json requires membrane/membrane ^0.8.2 -> satisfiable by membrane/membrane[0.8.2].
    - cebe/php-openapi 1.7.0 requires symfony/yaml ^3.4 || ^4 || ^5 || ^6 -> found symfony/yaml[v3.4.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.4.x-dev] but it conflicts with your root composer.json require (7.1.*).
    - membrane/membrane 0.8.2 requires cebe/php-openapi ^1.7 -> satisfiable by cebe/php-openapi[1.7.0].`

**Comment by carnage** [comment]
We switched the reader to use devizzent/cebe-php-openapi instead of the original, this one supports symfony 7 so should work now.

**Comment by developers-shared** [comment]
Can you please let me know once it is released because based on https://github.com/membrane-php/openapi-router/blob/0.5.0/composer.json#L18 it is still cebe/php-openapi 😄

**Comment by carnage** [comment]
Ah, I don't think that should be there any more; we built our own reader abstraction layer which the router & core depends on so they shouldn't need to reference that lib directly.

**Comment by carnage** [comment]
New releases published, give them a go and LMK if it all works now

**Comment by developers-shared** [comment]
Works like a charm now, thanks a lot Chris! 🙇
